version: "3"
services:
  postgres:
    image: "postgres:14.1"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis:6.2.6"
  api:
    depends_on:
      - postgres
      - redis
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - "./server:/app"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGDATABASE=postgres
  worker:
    depends_on:
      - redis
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - "./worker:/app"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    # "stdin_open: true" required for React
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - "./client:/app"
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "5000:80"
